### ISSUE TITLE
Allow waterlogging of the lamp fruit

### ISSUE THREAD

**Issue by WenXin20** [DcZipPL/lightestlampsmod#1]
Minecraft v1.14.4
Lightest Lamp v2.0.2

If waterlogging of the Lamp Fruit is added, this could make for a very good underwater decoration.

The hitbot of the Lamp Fruit is also a bit too big.

**Comment by DcZipPL** [comment]
Thank you for suggestion! These features are added in version [3.1.1](https://www.curseforge.com/minecraft/mc-mods/lightest-lamps/files/2855208)
