### ISSUE TITLE
Unable to auto input resource into gas centrifuge

### ISSUE THREAD

**Issue by mmis1000** [DcZipPL/lightestlampsmod#10]
**Describe the bug**
Use hopper, mekanism transporter, and probably all other auto input methods to fill glow stone into machaine does not work

**To Reproduce**
1. Put a hopper on the top of machine
2. Put some glow stone into hopper

**Expected behavior**
The glow stone goes into the machine resource slot

**Actual behavior**
nothing happened

**Screenshots**
![圖片](https://user-images.githubusercontent.com/2993977/85937689-a376cb00-b938-11ea-858a-929c9c0e0248.png)

**Versions (please complete the following information):**
 - Forge: 31.2.20
 - Minecraft: 1.15.2
 - Mod: 3.4.2
 - Other Mods: See [ATM5-2.5](https://www.curseforge.com/minecraft/modpacks/all-the-mods-5/files/2986305)

**Additional context**

**Comment by DcZipPL** [comment]
Bug is fixed in version 3.4.3. You need only wait until modpack creator updates mod.
