### ISSUE TITLE
Question about 1.16.3 version of the mod

### ISSUE THREAD

**Issue by Oct0bass** [DcZipPL/lightestlampsmod#14]
**Describe the bug**
Go mark this as invalid or whatever, I just have some questions about the mod and don't know where else to ask them:
1) What is the "Anti-Lamp"?  What does it do?
2) Is there plans for 1.16.2 / 1.16.3?  I'm not asking you to do anything, just want to know if you have plans.
3) Where can I ask questions like this in the future so I don't clutter your bug tracker with non-bugs?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A
**Versions (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by DcZipPL** [comment]
1. currently nothing,
2. Yes, currently I'm waiting for better mappings,
3. You can ask on Curseforge or here.

**Comment by Oct0bass** [comment]
Thank you
