### ISSUE TITLE
Crash while cheking recipes

### ISSUE THREAD

**Issue by aburone** [DcZipPL/lightestlampsmod#15]
Upon checking some recipes (one of the dusts last time) the game crashes to desktop

**Versions (please complete the following information):**
 - Forge: 35.0.16
 - Minecraft: 1.16.4
 - Mod: Lightest Lamps 4.0.6 (FORGE | 1.16.3)

**Additional context**
[crash-2020-11-26_19.00.33-client.txt](https://github.com/DcZipPL/lightestlampsmod/files/5605152/crash-2020-11-26_19.00.33-client.txt)

**Comment by SalmonSays** [comment]
Here to confirm this crash still happens on Forge 35.1.37, using JEI to look at recipes and when I check what the Gas Centrifuge does it crashes.

**Comment by FerroEduardo** [comment]
It still crashes when checking the recipe of **Neon Pile**

- Forge 36.0.42
- JEI 7.6.1.71
- Minecraft 1.16.5
- Mod: Lightest Lamps 4.0.6 (FORGE | 1.16.3)
