### ISSUE TITLE
Warning "exception loading blockstate definition"

### ISSUE THREAD

**Issue by ghost** [DcZipPL/lightestlampsmod#19]
**Describe the bug**

**To Reproduce**
1. Load client
2. read latest.log

**Expected behavior**
expected these warnings not to appear

**Versions (please complete the following information):**
Forge: forge-1.16.5-36.2.19-installer
Minecraft: 1.16.5
lightestlamp-4.0.7

**Additional context**
text file 
[error3.txt](https://github.com/DcZipPL/lightestlampsmod/files/7630034/error3.txt)

**Comment by DcZipPL** [comment]
Fixed in 4.5.0b
