### ISSUE TITLE
Omega Lamp broken texture

### ISSUE THREAD

**Issue by Yamza** [DcZipPL/lightestlampsmod#2]
Can be reproduced with no mods.

Forge: 30.0.24
lightestlampsmod-3.1.0
https://i.imgur.com/v5iWmjK.png

**Comment by DcZipPL** [comment]
Bug is fixed in version [3.1.1](https://www.curseforge.com/minecraft/mc-mods/lightest-lamps/files/2855208). Thank you for reporting 👍
