### ISSUE TITLE
crashes with jei

### ISSUE THREAD

**Issue by Yee5716** [DcZipPL/lightestlampsmod#22]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Forge: [e.g. 31.0.1]
 - Minecraft: [e.g. 1.15.2]
 - Mod: [e.g. 2.3.0]
 - Other Mods / Modpack?

**Additional context**

**Comment by DcZipPL** [comment]
Missing information and can not reproduce. Create new issue if bug happen again with detailed information.
