### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by dierks-m** [DcZipPL/lightestlampsmod#4]
**Describe the bug**
Dedicated server does not start when Lightest Lamps is installed.

**To Reproduce**
Install Lightest Lamps 3.2.1 on a dedicated Forge 31.0.1 server.

**Log file**
[Crash Log](https://pastebin.com/chcVBEk7)

**Versions (please complete the following information):**
 - Forge 31.0.1
 - Minecraft: 1.15.2
 - Mod: 3.2.1

**Comment by DcZipPL** [comment]
I will patch this bug today.

**Comment by DcZipPL** [comment]
Bug is fixed in version 3.2.3
