### ISSUE TITLE
Mod deletes on server when restart happens

### ISSUE THREAD

**Issue by Charmanth** [DcZipPL/lightestlampsmod#5]
**Describe the bug**
Whenever a Multiplayer Server restarts, the mod gets deleted from the mod folder.

**To Reproduce**
1. Have multiplayer server
2. Server restarts, either manually or through command
3. Server doesn't finish starting, because the mod is now missing.
4. Check the mod folder on server to verify.  It's missing.

**Expected behavior**
I expect the mod to stay uploaded to the server.  

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 31.1.12
 - Minecraft: 1.15.2
 - Mod: 3.3.0

**Additional context**
For what it's worth, the mod does stay downloaded locally to my client.

**Comment by DcZipPL** [comment]
What modpack you play or what mods are installed?

**Comment by Charmanth** [comment]
angelring 
AppleSkin
Aquaculture
bedspreads
BetterAdvancements
Biomes O Plenty
Bonzai Trees
Buzzier Bees
Caelus
Ceiling Torch
Craftable horse armor and saddles
Clay Worldgen
Comforts
Controlling
Corail Recycler
Cosmetic Armor Reworked
Crafting Station
Crafting Tweaks
Craft Tweaker
Cucumber
CUrios
DCIntegration
Doggy Talents
Double Slabs
Dungeon Crawl
Open Blocks Elevator Mod
Ender Compass
Extra Golems
Falling Tree
Fast Furnace
Fast Leaf Decay
Fast Work Bench
Forbidden Arcanus
Fruit Trees
Industrial Foregoing
Inventory Sorter
Inventory Tweaks
JEI
Kiwi
Klee Slabs
Lenient Creepers
Libnonymous
Lost Cities
mcjtylib
Mekanism
Mekanism Generators
Mekanism Tools
Metal Barrels
Minecolonies
Mining Helmet
Morpheus
Mousetweaks
Mystical Agriculture
Mystical Aggradditions
Nature's Compass
Nether Portal Fix
Placebo
ReAuth
Refined Storage
Refined Storage addons
Serene Seasons
Smoke
Spice of Life Carrot
Structurize
Swinging through grass
The one probe
titanium
toast control
corail tombstone
Tool Belt
Torch Master
Trash Slot
U team core
Useful Backpacks
Water strainer
Waystones
Wetstone
Xaeros Minimap
Xaeros worldmap

**Comment by DcZipPL** [comment]
I see no problem after restarting. Strange

**Comment by DcZipPL** [comment]
If somebody has same problem please create new issue.
