### ISSUE TITLE
Glowing Glass Breaks even with Silk Touch

### ISSUE THREAD

**Issue by OfficialStamper** [DcZipPL/lightestlampsmod#8]
Extremely annoying that when building; if you misplace a glowing glass block it will be broken if you attempt to mine it back

The one probe reports 'no tool', thus anything used from; hand, to silk touch enchanted pick axe will break the block returning a random number of glowstone dust only.

Can you please either introduce a tool that allows 'wrench' style block breaking or at least allow silk touch.

**Comment by DcZipPL** [comment]
Glowing Glass drops normal block in 3.4.2.
